name: OWASP Dependency Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-check:
    runs-on: ubuntu:22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.xx' # Specify the Node.js version to use

    - name: Install dependencies
      run: npm install

    - name: Install OWASP Dependency Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip
        unzip dependency-check-6.5.3-release.zip -d dependency-check
        sudo chmod +x dependency-check/bin/dependency-check.sh


